### ISSUE TITLE
No module named 'demo.animate'

### ISSUE THREAD

**Issue by IceCocoecI** [guoqincode/AnimateAnyone-unofficial#60]
when running "python3 -m demo.gradio_animate"

An error has occurred

Traceback (most recent call last):
  File "/home/wyfx/anaconda3/envs/AnimateAnyone-unofficial/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wyfx/anaconda3/envs/AnimateAnyone-unofficial/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/projects/AnimateAnyone-unofficial/demo/gradio_animate.py", line 8, in <module>
    from demo.animate import AnimateAnyone
ModuleNotFoundError: No module named 'demo.animate'

It looks like the demo directory is missing animate modules

**Comment by guoqincode** [comment]
We will release this along with the pre-trained model.
